# Generated by Django 6.0.4 on 2026-05-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videosource',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
