# Generated by Django 6.0.4 on 2026-05-09 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_groups_user_user_permissions'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HLSStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_playlist_url', models.URLField(max_length=1000)),
                ('variants', models.JSONField(default=dict)),
                ('bandwidth_info', models.JSONField(default=dict)),
                ('video_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.videosource')),
            ],
        ),
        migrations.CreateModel(
            name='StreamHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('quality', models.CharField(max_length=10)),
                ('bandwidth_mbps', models.FloatField(blank=True, null=True)),
                ('buffer_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usersession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('series_id', models.PositiveIntegerField(blank=True, null=True)),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('last_position_seconds', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('percent_completed', models.FloatField(default=0)),
                ('quality', models.CharField(blank=True, max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_watched_at'],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='ContinueWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('last_position_seconds', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continue_watching', to=settings.AUTH_USER_MODEL)),
                ('watch_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streaming.watchhistory')),
            ],
        ),
    ]
